package com.yn.go.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_admin", "id", Admin.class);
		arp.addMapping("t_news", "id", News.class);
		arp.addMapping("t_tournament", "id", Tournament.class);
		arp.addMapping("t_tournament_detail", "id", TournamentDetail.class);
		arp.addMapping("t_training_address", "id", TrainingAddress.class);
		arp.addMapping("t_user", "id", User.class);
	}
}

