package com.yn.go.common.model;

import com.yn.go.common.model.base.BaseAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Admin extends BaseAdmin<Admin> {
	public static final Admin dao = new Admin().dao();
	
	public boolean checkAdminAndPassword(String name,String password){
		
		Admin admin = findFirst("select id from t_admin where name =? and password =?",name,password);
		if(admin==null){
			return false;
		}
		return true;
	}
}
