package com.yn.go.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.yn.go.common.BuildParams;
import com.yn.go.common.BuildSql;
import com.yn.go.common.Filters;
import com.yn.go.common.model.base.BaseNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class News extends BaseNews<News> {
	public static final News dao = new News().dao();
	
	public Page<Record> paginate(int pageNumber,int pageSize,Filters filters){
		StringBuilder sql =new StringBuilder()
		.append("from t_news a  left join t_admin c on(a.admin_id=c.id)")
		.append(BuildSql.getInstance().build(filters, new BuildParams()));
		return Db.paginate(pageNumber, pageSize, "select a.*,a.create_datetime as createDatetime,c.name",sql.toString());
	}
	
	public List<Record> findList(int count){
		return Db.find("select id,title,DATE_FORMAT(create_datetime,'%m-%d') as createDatetime from t_news order by create_datetime limit 0,?", count);
	} 
}
