package com.yn.go.common.model;

import com.yn.go.common.model.base.BaseTournamentDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TournamentDetail extends BaseTournamentDetail<TournamentDetail> {
	public static final TournamentDetail dao = new TournamentDetail().dao();
}
