package com.yn.go.common.model;

import com.yn.go.common.model.base.BaseTournament;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tournament extends BaseTournament<Tournament> {
	public static final Tournament dao = new Tournament().dao();
}
