package com.yn.go.common.model;

import com.yn.go.common.model.base.BaseTrainingAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrainingAddress extends BaseTrainingAddress<TrainingAddress> {
	public static final TrainingAddress dao = new TrainingAddress().dao();
}
