package com.yn.go.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public M setPassward(java.lang.String passward) {
		set("passward", passward);
		return (M)this;
	}

	public java.lang.String getPassward() {
		return get("passward");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setCard(java.lang.String card) {
		set("card", card);
		return (M)this;
	}

	public java.lang.String getCard() {
		return get("card");
	}

	public M setWechat(java.lang.String wechat) {
		set("wechat", wechat);
		return (M)this;
	}

	public java.lang.String getWechat() {
		return get("wechat");
	}

	public M setQq(java.lang.String qq) {
		set("qq", qq);
		return (M)this;
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public M setDanGrading(java.lang.Integer danGrading) {
		set("dan_grading", danGrading);
		return (M)this;
	}

	public java.lang.Integer getDanGrading() {
		return get("dan_grading");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setAdminId(java.lang.Integer adminId) {
		set("admin_id", adminId);
		return (M)this;
	}

	public java.lang.Integer getAdminId() {
		return get("admin_id");
	}

	public M setUnit(java.lang.String unit) {
		set("unit", unit);
		return (M)this;
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public M setCertificateNumber(java.lang.String certificateNumber) {
		set("certificate_number", certificateNumber);
		return (M)this;
	}

	public java.lang.String getCertificateNumber() {
		return get("certificate_number");
	}

	public M setCertificateDatetime(java.util.Date certificateDatetime) {
		set("certificate_datetime", certificateDatetime);
		return (M)this;
	}

	public java.util.Date getCertificateDatetime() {
		return get("certificate_datetime");
	}

	public M setCreateDatetime(java.util.Date createDatetime) {
		set("create_datetime", createDatetime);
		return (M)this;
	}

	public java.util.Date getCreateDatetime() {
		return get("create_datetime");
	}

	public M setUpdateDatetime(java.util.Date updateDatetime) {
		set("update_datetime", updateDatetime);
		return (M)this;
	}

	public java.util.Date getUpdateDatetime() {
		return get("update_datetime");
	}

}
