package com.yn.go.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTournamentDetail<M extends BaseTournamentDetail<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTId(java.lang.Integer tId) {
		set("t_id", tId);
		return (M)this;
	}

	public java.lang.Integer getTId() {
		return get("t_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setPayType(java.lang.Integer payType) {
		set("pay_type", payType);
		return (M)this;
	}

	public java.lang.Integer getPayType() {
		return get("pay_type");
	}

	public M setPayAccount(java.lang.String payAccount) {
		set("pay_account", payAccount);
		return (M)this;
	}

	public java.lang.String getPayAccount() {
		return get("pay_account");
	}

	public M setAPayerId(java.lang.Integer aPayerId) {
		set("a_payer_id", aPayerId);
		return (M)this;
	}

	public java.lang.Integer getAPayerId() {
		return get("a_payer_id");
	}

	public M setCreateDatetime(java.util.Date createDatetime) {
		set("create_datetime", createDatetime);
		return (M)this;
	}

	public java.util.Date getCreateDatetime() {
		return get("create_datetime");
	}

	public M setUpdateDatetime(java.util.Date updateDatetime) {
		set("update_datetime", updateDatetime);
		return (M)this;
	}

	public java.util.Date getUpdateDatetime() {
		return get("update_datetime");
	}

	public M setFPayerId(java.lang.Integer fPayerId) {
		set("f_payer_id", fPayerId);
		return (M)this;
	}

	public java.lang.Integer getFPayerId() {
		return get("f_payer_id");
	}

	public M setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
		return (M)this;
	}

	public java.lang.String getOrderId() {
		return get("order_id");
	}

}
